### PR TITLE
Rename variables

### PR DESCRIPTION
**Pull request by Jono20201**
I feel that the variable names are a little too open, and worry that they might conflict in my existing application either now or in the future. I'd like to proprose renaming the variables used within this plugin to avoid clashes.

I realise this is a breaking change, so would need to be included in a new major release.

### CODE REVIEW

**Comment by christabor** [comment]
Sorry for the delay. I am open to this idea. Just a couple things:

1. Update the package.json and any docs to reflect the current version, so if it gets published to NPM it will be known as a breaking change (eg. 2.0.1 iirc).
2. Also include the minified data so folks quickly downloading it from source will not get confused or tripped up.

Otherwise, LGTM 👍

**Comment by Jono20201** [comment]
@christabor 

I've updated the package.json to be v2.0.1. I did run gulp but due to this been a simple change with variable names there were no changes to the outputted CSS file -- which was to be expected. I also see no reference to the variable names in any current documentation.

**Comment by Jono20201** [comment]
Should I close this?

**Comment by christabor** [comment]
Wow, sorry, I don't really check this project anymore. I think this change is good, but github thinks there are conflicts to resolve. I can merge it after that.

**Comment by Jono20201** [comment]
@christabor Should be good to go.

**Comment by christabor** [comment]
Thanks!

**Pull request merged**
